### ISSUE TITLE
"Read numbers and punctuations based on surrounding text" doesn't work

### ISSUE THREAD

**Issue by ghost** [Mahmood-Taghavi/dual_voice#6]
Hello. NVDA read dot in sentence "Привет. Мой друг" as "dot". But i expect the "dot" to be read in my native language.

I set Microsoft Mark - English as primary voice, i set Microsoft Irina - Russian as secondary voice.
Parameter "Use the secondary voice for reading Latin text instead of non-Latin" is unchecked.
Parameter "Prioritize non-Latin text over Latin text" is unchecked.
Parameter "Read numbers and punctuations based on surrounding text" is checked.

P.S. In window "Symbol pronunciation (English)" and window "Symbol pronunciation (Русский)" I tried to set parameter  "send actual symbol to synthesizer" = always for "." and for ". sentence ending". But this doesn't work either.

**Comment by Mahmood-Taghavi** [comment]
Thank you for highlighting this issue. I will try to fix this issue in the future.

**Comment by Mahmood-Taghavi** [comment]
This is not actually a bug in the dual voice addon. You need just to do some settings.
In fact, the NVDA always sends "dot text" instead of a "dot symbol" when its user interface is English.
So, first you need to switch to your local user interface using the NVDA general settings dialog.
Then, if you have selected an English voice as the primary voice you need to uncheck the third checkbox in the NVDA speech settings which is the translation of "Trust voice's language when processing characters and symbols" item in your local languages. 
I tested this situation using NVDA 2020.1 and a Persian voice for processing non-Latin text and it works fine.

**Comment by ghost** [comment]
With that settings it always read russian dots even in english sentences.

**Comment by Mahmood-Taghavi** [comment]
The NVDA sends the equivalent text of the dot symbol to the speech driver, so it seems there is no a reliable way to fix this issue.

**Comment by ghost** [comment]
OK, Thank you for your help anyway.
